machine:
  environment:
    GYM_CODE_SIGNING_IDENTITY: "iPhone Distribution: Acme Inc. (FAKEVALUE)"
    XCODE_SCHEME: "Unity-iPhone"
    XCODE_PROJECT: "Unity-iPhone.xcodeproj"
      
    steps:
      # Commands will execute in macOS container
      # with Xcode 9.0 installed
      - chmod a+x ./Scripts/install.sh
      - chmod a+x ./Scripts/build.sh
      - bash ./Scripts/install.sh
      - bash ./Scripts/build.sh
