version: 2

jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - chmod a+x ./Scripts/install.sh
      - chmod a+x ./Scripts/build.sh
      -./Scripts/install.sh
      - ./Scripts/build.sh
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
