jobs:
  build:
    machine: true
      
    steps:
    - checkout
    - run: apt-get install -y sudo # https://discuss.circleci.com/t/sudo-command-not-found/14208/4
    - run: ls -al /bin/sh && sudo rm /bin/sh && sudo ln -s /bin/bash /bin/sh && ls -al /bin/sh
    - run: chmod a+x ./Scripts/install.sh
    - run: chmod a+x ./Scripts/build.sh
    - run: ./Scripts/install.sh
    - run: ./Scripts/build.sh 
